# -*- coding: utf-8 -*-
"""project_colab

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/143PqtSV_dCq3cRb5CQtOA7VbfaqFuFJz
"""

from google.colab import files

#Cargar datos a colab
load = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""**Exploración inicial**"""

oil = pd.read_csv('fish_oil.csv')
oil.head()

# Obtener información sobre el DataFrame
oil.info()

# Obtener estadísticas descriptivas de las columnas numéricas
oil.describe()

# Columnas (fecha,muestra,grasa,proteina,humedad,acidos_grasos_saturados,acidos_grasos_insaturados,vitaminas)

oil.columns

"""**Visualización de datos**"""

# Diagrama de dispersión fat(grasa) vs protein(proteina)
sns.scatterplot(data = oil , x = 'fat' , y = 'protein')
plt.title('fat to protein ratio')
plt.show()

"""**Análisis de tendencias**"""

# Convertir la columna 'fecha' al tipo de dato 'datetime'
oil['date'] = pd.to_datetime(oil['date'])

# Gráfico de línea para la tendencia de grasa y proteina a lo largo del tiempo
sns.lineplot(data = oil , x = 'date' , y = 'fat' , label = 'Fat(Grasa)')
sns.lineplot(data = oil , x = 'date' , y = 'protein' , label = 'Protein(Proteína)')
plt.title('Fat and protein trend over time')
plt.ylabel('Values')
plt.show()

"""**Análisis de calidad**

que la grasa esté por encima del 12% y la humedad por debajo del 6%
"""

# Verificar si hay muestras que no cumplan con los criterios de calidad
quality = oil[(oil['fat'] < 12 ) | (oil['moisture'] > 6 )]
print(quality)

